

set(NRAPPKIT_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/nrappkit")
set(NRAPPKIT_ROOT_INCLUDE ${NRAPPKIT_ROOT}/src)
add_subdirectory("${NRAPPKIT_ROOT}")
set(ERIZO_CMAKE_CXX_FLAGS "${ERIZO_CMAKE_CXX_FLAGS} -DNO_REG_RPC=1 -DHAVE_VFPRINTF=1 -DRETSIGTYPE=void -DNEW_STDIO -DHAVE_STRDUP=1 -DHAVE_STRLCPY=1 -DHAVE_LIBM=1 -DHAVE_SYS_TIME_H=1 -DTIME_WITH_SYS_TIME_H=1 -D__UNUSED__=\"__attribute__((unused))\"")
set(ERIZO_CMAKE_CXX_FLAGS "${ERIZO_CMAKE_CXX_FLAGS} -DLINUX -DNOLINUXIF")

list(APPEND NRAPPKIT_INCLUDE 
  "${NRAPPKIT_ROOT_INCLUDE}/event"
  "${NRAPPKIT_ROOT_INCLUDE}/log"
  "${NRAPPKIT_ROOT_INCLUDE}/plugin"
  "${NRAPPKIT_ROOT_INCLUDE}/registry"
  "${NRAPPKIT_ROOT_INCLUDE}/share"
  "${NRAPPKIT_ROOT_INCLUDE}/stats"
  "${NRAPPKIT_ROOT_INCLUDE}/util"
  "${NRAPPKIT_ROOT_INCLUDE}/util/libekr"
  "${NRAPPKIT_ROOT_INCLUDE}/port/generic/include"
  "${NRAPPKIT_ROOT_INCLUDE}/port/generic/include/sys"
  "${NRAPPKIT_ROOT_INCLUDE}/crypto"
  "${NRAPPKIT_ROOT_INCLUDE}/ice"
  "${NRAPPKIT_ROOT_INCLUDE}/net"
  "${NRAPPKIT_ROOT_INCLUDE}/stun"
  "${NRAPPKIT_ROOT_INCLUDE}/port/linux/include" 
  "${NRAPPKIT_ROOT_INCLUDE}/port/linux/include/sys"
  )



