add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/webrtc")
set(ERIZO_CMAKE_CXX_FLAGS "${ERIZO_CMAKE_CXX_FLAGS} -DWEBRTC_POSIX")
set(ERIZO_CMAKE_CXX_FLAGS "${ERIZO_CMAKE_CXX_FLAGS} -Werror -fPIC -DWEBRTC_LINUX")

